spring:
  datasource:
    url: jdbc:h2:mem:testregistedb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8085

logging:
  level:
    root: INFO
    org:
      springframework:
        orm: DEBUG
        jdbc: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8005/eureka/